# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summarymodule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='date',
            new_name='article_date',
        ),
    ]
