# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 13:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarymodule', '0002_auto_20170118_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='news',
            name='article_date',
            field=models.CharField(max_length=100),
        ),
    ]
