# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarymodule', '0003_auto_20170118_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='article_description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='news',
            name='article_url',
            field=models.CharField(max_length=250),
        ),
    ]
