# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summarymodule', '0006_news_article_img_href'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='article_img_href',
        ),
    ]
