# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarymodule', '0007_remove_news_article_img_href'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='article_img_href',
            field=models.CharField(default='', max_length=250),
        ),
    ]
