# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('summarymodule', '0008_news_article_img_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='create_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
