# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarymodule', '0009_auto_20170123_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='article_date',
            field=models.DateTimeField(),
        ),
    ]
