# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarymodule', '0010_auto_20170125_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='rating_dislikes',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='news',
            name='rating_likes',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False),
        ),
    ]
