# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarymodule', '0011_auto_20170215_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='rating_dislikes',
        ),
        migrations.RemoveField(
            model_name='news',
            name='rating_likes',
        ),
        migrations.AddField(
            model_name='news',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
