# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarymodule', '0012_auto_20170215_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='news',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='news',
            name='vote_score',
        ),
        migrations.AddField(
            model_name='news',
            name='vote_down',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='vote_up',
            field=models.IntegerField(null=True),
        ),
    ]
