# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarymodule', '0013_auto_20170215_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='vote_down',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='news',
            name='vote_up',
            field=models.IntegerField(default=0),
        ),
    ]
