# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 10:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('summarymodule', '0014_auto_20170215_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField()),
                ('last_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('id_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summarymodule.News')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserNews',
            },
        ),
    ]
