# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-25 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('summarymodule', '0015_usernews'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('id_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summarymodule.News')),
            ],
            options={
                'db_table': 'NewsTags',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=200)),
                ('tag_score', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Tags',
            },
        ),
        migrations.AddField(
            model_name='newstags',
            name='id_tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summarymodule.Tags'),
        ),
    ]
