# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-25 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statisticsapp', '0002_tags_tag_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newstags',
            name='id_news',
        ),
        migrations.RemoveField(
            model_name='newstags',
            name='id_tags',
        ),
        migrations.DeleteModel(
            name='NewsTags',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
