# Generated by Django 2.0.4 on 2018-05-14 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registerapp', '0005_userprofile_used_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpasschange',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
