# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogArticles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=120)),
                ('blog_description', models.CharField(max_length=200)),
                ('blog_text', models.TextField()),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
