# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170221_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticles',
            name='blog_image',
            field=models.ImageField(default='blog_img/None/no-img.jpg', upload_to='blog_img/'),
        ),
    ]
