# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170221_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticles',
            name='blog_image',
            field=models.FileField(default='None/no-img.jpg', upload_to='image/%Y/%m/%d'),
        ),
    ]
