# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170221_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticles',
            name='blog_image',
            field=models.FileField(default='None/no-img.jpg', null=True, upload_to='image/%Y/%m/%d'),
        ),
    ]
