# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170221_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticles',
            name='vote_down',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogarticles',
            name='vote_up',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogarticles',
            name='blog_image',
            field=models.FileField(default='settings.MEDIA_ROOT/None/no-img.jpg', null=True, upload_to='image/%Y/%m/%d'),
        ),
    ]
