# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_userblogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticles',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogarticles',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogarticles',
            name='blog_image',
            field=models.ImageField(blank=True, default='settings.MEDIA_ROOT/None/no-img.jpg', height_field='height_field', null=True, upload_to='image/%Y/%m/%d', width_field='width_field'),
        ),
    ]
