# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 11:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0010_auto_20170227_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticles',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogarticles',
            name='blog_image',
            field=models.ImageField(blank=True, default='none/no-img.jpg', height_field='height_field', null=True, upload_to='image/%Y/%m/%d', width_field='width_field'),
        ),
    ]
